security:
    encoders:
        Eduteca\EdutecaBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
         users:
             entity: { class EdutecaBundle:User }

    firewalls:
    
        admin:
            pattern:    ^/admin
            form_login:
                check_path: /admin/login_check
                login_path: /loginAdmin
            logout:
                path:   /admin/logout
                target: /admin
            anonymous: ~
            
        web:
            pattern:    ^/
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path:   /logout
                target: /
            anonymous: ~
    
    access_control:
        - { path: ^/prepareUpload, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }

